PKR/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import pkr_user.views as user_views

urlpatterns = [
    url(r'^$', user_views.home, name = 'home'),
    url(r'^user/', include('pkr_user.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/', user_views.user_logout, name="logout"),
    url(r'^dashboard/', user_views.dashboard, name = 'dashboard'),
    url(r'^items/', user_views.items, name='item'),
    url(r'^request_items/', user_views.items_request, name='item_request'),
    url(r'^add_product', user_views.add_product, name= 'add_product'),
    url(r'^update_stock', user_views.update_stock, name = 'update_stock'),
]

pkr_user/urls.py
from django.conf.urls import url
from . import views

# SET THE NAMESPACE!
app_name = 'pkr_user'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

pkr_user/models.py
from django.db import models
from django.contrib.auth.models import User

class Customer(models.Model):
    customerNumber = models.CharField(primary_key=True, max_length=128, unique=True)
    customerFirstName = models.CharField(max_length=64, default="")
    customerLastName = models.CharField(max_length=64, default="")
    contactFirstName = models.CharField(max_length=64)
    contactLastName = models.CharField(max_length=64)
    phone = models.CharField(max_length=15)
    addressOne = models.CharField(max_length=128)
    addressTwo = models.CharField(max_length=128, blank=True, null=True)
    city = models.CharField(max_length=64)
    postalCode = models.CharField(max_length=8)
    country = models.CharField(max_length=64)
    creditLimit = models.IntegerField(default=100)
    signUpDate = models.DateField(blank=True, null=True)
    def __str__(self):
        return self.customerNumber

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    customerNumber = models.ForeignKey(Customer)
    def __str__(self):
        return self.user.username

class ProductLine(models.Model):
    productLine = models.CharField(primary_key=True, max_length=128, unique=True)
    textDescription = models.TextField(blank=True, null=True)
    htmlDescription = models.TextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True)
    def __str__(self):
        return self.productLine

class Product(models.Model):
    class Meta():
        unique_together = (('customerNumber', 'productCode'),)
    productCode = models.CharField(primary_key=True, max_length=128, unique=True)
    productName = models.CharField(max_length=128)
    productLine = models.ForeignKey(ProductLine)
    productScale = models.CharField(max_length=128, null=True, blank=True)
    productDescription = models.TextField(blank=True, null=True)
    buyPrice = models.FloatField()
    MSRP = models.FloatField(blank=True, null=True)
    customerNumber = models.ForeignKey(Customer, null=True, default='')
    def __str__(self):
        return self.productCode

class Order(models.Model):
    orderNumber = models.CharField(primary_key=True, max_length=128, unique=True)
    orderDate = models.DateField()
    requiredDate = models.DateField()
    shippedDate = models.DateField(blank=True, null=True)
    status = models.CharField(max_length=32)
    comments = models.CharField(max_length=256)
    customerNumber = models.ForeignKey(Customer)
    def __str__(self):
        return self.orderNumber

class OrderDetail(models.Model):
    orderNumber = models.ForeignKey(Order)
    productCode = models.ForeignKey(Product)
    quantityOrdered = models.IntegerField()
    priceEach = models.IntegerField()
    orderLineNumber = models.IntegerField()
    def __str__(self):
        return self.orderNumber

class Payment(models.Model):
    customerNumber = models.ForeignKey(Customer)
    checkNumber = models.CharField(primary_key=True, max_length=128, unique=True)
    paymentDate = models.DateField()
    amount = models.FloatField()

    def __str__(self):
        return self.customerNumber

class Stock(models.Model):
    customerNumber = models.ForeignKey(Customer)
    dateRecord = models.DateField()
    productCode = models.ForeignKey(Product)
    quantity = models.IntegerField()

    def __str__(self):
        return str(self.customerNumber)

pkr_user/forms.py
from django import forms
from django.contrib.auth.models import User
import pkr_user.models as models


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'password')

class CustomerForm(forms.ModelForm):
    class Meta():
        model = models.Customer
        labels = {
            "customerFirstName" : "First Name",
            "customerLastName" : "Last Name",
            "contactFirstName" : "Contact First Name",
            "contactLastName" : "Contact Last Name",
            "postalCode" : "Postal Code",
            "addressOne" : "Address Line One",
            "addressTwo" : "Address Line Two",
        }
        exclude = ('creditLimit', 'signUpDate', 'customerNumber')

class ProductForm(forms.ModelForm):
    class Meta():
        model = models.Product
        labels = {
            "productCode" : "Product Code",
            "productName" : "Product Name",
            "productLine" : "Product Line",
            "quantityInStock" : "Quantity",
            "buyPrice" : "Buy Price",
            "MSRP" : "Retail Price",
        }
        exclude = ('productScale', 'productDescription', 'customerNumber')

class StockForm(forms.ModelForm):
    class Meta():
        model = models.Stock
        exclude = ('productCode', 'customerNumber', 'dateRecord')

pkr_user/views.py
from django.shortcuts import render
import pkr_user.forms as forms
import pkr_user.models as models
from pkr_user.models import UserProfile
# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.http import JsonResponse
from django.contrib import messages
import uuid
import csv

def home(request):
    return render(request, 'pkr_user/home.html')

@login_required
def dashboard(request):
    product_form = forms.ProductForm
    stock_form = forms.StockForm
    error = messages.get_messages(request)
    return render(request, 'pkr_user/dashboard.html', {"product_form" : product_form, "stock_form" : stock_form, "error" : error})

@login_required
def add_product(request):
    current_user = request.user
    product_form = forms.ProductForm(data=request.POST)
    stock_form = forms.StockForm(data=request.POST)
    profile = models.UserProfile.objects.values_list('customerNumber').get(user=current_user)
    curr_customer = models.Customer.objects.get(customerNumber=profile[0])
    if product_form.is_valid() and stock_form.is_valid():
        product = product_form.save()
        product.customerNumber = curr_customer
        product.save()
        stock = models.Stock.objects.get_or_create(productCode=product, dateRecord=timezone.now(), quantity=0, customerNumber=curr_customer)[0]
        print(stock_form.cleaned_data['quantity'])
        stock.quantity = stock_form.cleaned_data['quantity']
        stock.save()
    else:
        print(product_form.errors)
    return HttpResponseRedirect(reverse('dashboard'))

def update_stock(request):
    print("Updating Stock!")
    current_user = request.user
    profile = models.UserProfile.objects.values_list('customerNumber').get(user=current_user)
    curr_customer = models.Customer.objects.get(customerNumber=profile[0])
    if request.method == 'POST':
        quantity = request.POST.get('quantity')
        product_id = models.Product.objects.get(productCode=request.POST.get('id'))
        product_name = models.Product.objects.values_list('productName').get(productCode=request.POST.get('id'))
        try:
            exist_stock = models.Stock.objects.get(customerNumber=curr_customer, productCode=product_id, dateRecord=timezone.now())
            print(product_name)
            messages.add_message(request, messages.INFO, 'You cannot update ' + product_name[0] + ' again today.')
            return HttpResponseRedirect(reverse('dashboard'))
        except models.Stock.DoesNotExist:
            new = models.Stock.objects.get_or_create(productCode=product_id, dateRecord=timezone.now(), quantity=quantity, customerNumber=curr_customer)[0]
            new.save()
    print("End Path!")
    return HttpResponseRedirect(reverse('dashboard'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = forms.UserForm(data=request.POST)
        customer_form = forms.CustomerForm(data = request.POST)
        if user_form.is_valid() and customer_form.is_valid():
            customer = customer_form.save()
            customer.signUpDate = timezone.now()
            customer.customerNumber = uuid.uuid4()
            customer.creditLimit = 100
            customer.save()
            user = user_form.save()
            user.set_password(user.password)
            user.first_name = customer.customerFirstName
            user.last_name = customer.customerLastName
            user.save()
            user_customer = UserProfile(customerNumber=customer, user=user)
            user_customer.save()
            registered = True
        else:
            print(user_form.errors, customer_form.errors)
    else:
        user_form = forms.UserForm()
        customer_form = forms.CustomerForm()
    return render(request, 'pkr_user/register.html',
                { 'user_form' : user_form,
                  'customer_form' : customer_form,
                  'registered' : registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('home'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'pkr_user/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

@login_required
def items(request): # GET endpoint should work in dashboard.html
    #query db to get table of (itemID, itemName) tuples
    current_user = request.user
    if request.user.is_authenticated():
        profile = models.UserProfile.objects.values_list('customerNumber').get(user=current_user)
        curr_customer = models.Customer.objects.get(customerNumber=profile[0])
        items = models.Product.objects.values_list('productCode', 'productName').filter(customerNumber=curr_customer).distinct('productName')
        out = []
        for item in items:
            out.append({"id": item[0], "name": item[1]})
        return JsonResponse({"arr": out})
    else:
        return JsonResponse({"arr": [{}]})

@login_required
def items_request(request):
    current_user = request.user
    product_code = request.META['QUERY_STRING'].split("=")[1]
    product = models.Product.objects.get(productCode=product_code)
    output = []
    if request.user.is_authenticated():
        profile = models.UserProfile.objects.values_list('customerNumber').get(user=current_user)
        curr_customer = models.Customer.objects.get(customerNumber=profile[0])
        stocks = models.Stock.objects.values_list('productCode', 'dateRecord', 'quantity').filter(customerNumber=curr_customer, productCode=product).order_by('dateRecord')
        for item in stocks:
            output.append({"dateRecord": item[1], "quantity": item[2]})
            #writer.writerow([item[1], item[2]])
    return JsonResponse({"output": output})

templates/pkr_user/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>PKR</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel = "stylesheet" href="{% static "pkr_user/home.css" %}"/>
    {% block links %}
    {% endblock %}
  </head>
  {% block script_block %}
  {% endblock %}
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          {# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'home' %}">PKR</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'pkr_user:register' %}">Register</a></li>
            <li><a class="navbar-link" href="{% url 'pkr_user:user_login' %}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container">
    {% block status %}
    {% endblock %}
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
  <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

templates/pkr_user/dashboard.html
{% extends 'pkr_user/base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block links %}
<link rel = "stylesheet" href="{% static "pkr_user/dashboard.css" %}"/>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
{% endblock %}

{% block script_block %}
<script src="http://d3js.org/d3.v3.min.js"></script>
<script>
  var items = null; // List of items in the user's inventory

  function getItems() {
    fetch('/items', {credentials: "include"}) // endpoint should return a list of js objects with 2 attributes for each:
                                              // name (the name of the item) and
                                              // id (the id number of the item)
    .then(res => res.json())
    .then(items => {
      var list = document.getElementById("itemsContainer") // clear out the list if it exists already

      var select = document.getElementById("update_select")
      while (list.firstChild)
        list.removeChild(list.firstChild);
      while (select.firstChild)
        select.removeChild(select.firstChild);

      items.arr.forEach((item) => {                    // for each item returned, make a div to be added to the sidebar
        var row = document.createElement("div");
        var option = document.createElement("option")

        row.id = "p"+item.id;
        option.setAttribute("value", item.id)
        row.classList.add("itemRow");
        row.appendChild(document.createTextNode(item.name));
        option.appendChild(document.createTextNode(item.name));
        row.href = "#";
        row.addEventListener('click', e => loadChart(item.id)); // when div clicked, connect to server to get information needed to build chart

        link = document.createElement("a")
        select.appendChild(option)
        link.appendChild(row)
        list.appendChild(link)
      });
    });
  }

  function loadChart(id) {
    // Make a call to the endpoint to get info about an item and use that info to generate/display chart and put it in #chartDiv
    // for now, just printing the id of the item clicked
    fetch('/request_items?id=' + id, {credentials: "include"})
    .then(res => res.json())
    .then(res => {
      var list = document.getElementById("chartContainer") // clear out the list if it exists already
      var table = document.getElementById("itemValues")
      while (list.firstChild)
        list.removeChild(list.firstChild);
      while (table.firstChild)
        table.removeChild(table.firstChild)



      var margin = {top: 50, right: 50, bottom: 50, left: 60},
          width = 700 - margin.left - margin.right,
          height = 300 - margin.top - margin.bottom;

      // Parse the date / time
      var parseDate = d3.time.format("%Y-%m-%d").parse;

      // Set the ranges
      var x = d3.time.scale().range([0, width]);
      var y = d3.scale.linear().range([height, 0]);

      // Define the axes
      var xAxis = d3.svg.axis().scale(x)
          .orient("bottom").ticks(5);

      var yAxis = d3.svg.axis().scale(y)
          .orient("left").ticks(5);

      // Define the line
      var valueline = d3.svg.line()
          .x(function(d) { return x(d.dateRecord); })
          .y(function(d) { return y(d.quantity); });

      // Adds the svg canvas
      var text = d3.select("#p"+id).text()
      var header = d3.select("#chartContainer")
          .append("h2")
              .text(text)
      var svg = d3.select("#chartContainer")
          .append("svg")
              .attr("width", width + margin.left + margin.right)
              .attr("height", height + margin.top + margin.bottom)
          .append("g")
              .attr("transform",
                    "translate(" + margin.left + "," + margin.top + ")");

        // Get the data
        console.log(res.output)
        data = res.output;
            data.forEach(function(d) {
                d.dateRecord = parseDate(d.dateRecord);
                d.quantity = +d.quantity;

                row = document.createElement("tr")
                col1 = document.createElement("td")
                col2 = document.createElement("td")
                col1.appendChild(document.createTextNode(d.dateRecord))
                col2.appendChild(document.createTextNode(d.quantity))
                row.appendChild(col1)
                row.appendChild(col2)
                table.appendChild(row)
            });
        console.log(data)
            // Scale the range of the data
            range = d3.extent(data, function(d) { return d.quantity; })
            x.domain(d3.extent(data, function(d) { return d.dateRecord; }));
            y.domain([0, d3.max(data, function(d) { return d.quantity; })]);
            // Add the valueline path.
            svg.append("path")
                .attr("class", "line")
                .attr("d", valueline(data));

            // Add the X Axis
            svg.append("g")
                .attr("class", "x_axis")
                .attr("transform", "translate(0," + height + ")")
                .call(xAxis);

            // Add the Y Axis
            svg.append("g")
                .attr("class", "y_axis")
                .call(yAxis);

        });

  }
  d3.select("#links")
    .on("click", function(e){
      d3.event.stopPropagation()
      d3.select("#regulations")
        classed("none", d3.select(this).classed("none") ? false : true);
    })

    chartShowing = true;

    function toggle() {

      chartDiv = document.getElementById("chartContainer")
      tableDiv = document.getElementById("dataTable")
      button = document.getElementById("toggleButton")
      chartDiv.classList.toggle("none")
      tableDiv.classList.toggle("none")
      chartShowing = !chartShowing;
      button.innerHTML = (chartShowing)? "Show Table": "Show Graph";

    }
  window.addEventListener('load', e => getItems()); // get list when page is loaded
</script>
{% endblock %}

{% block status %}
  <p id="error">
    {% for message in error %}
      {{message}}
    {% endfor %}
  </p>
{% endblock %}

{% block body_block %}
<div class="container content row">
  <h1 style="margin-left: auto;">Dashboard</h1>
    <button class="btn btn-primary" data-toggle="modal" data-target="#addProductForm">Add New Product</button>
    <button class="btn btn-primary" data-toggle="modal" data-target="#addUpdateForm">Update Stock</button>
    <button id="toggleButton" class="btn btn-success" onclick="toggle()">Show Table</button>
  <div style="text-align:center; position: relative; max-width:384px; margin: 0 auto;">
    <div style="border-left: 1px solid #eee; width: 1px; position: absolute; left: 45px; height: 100%;"></div>
  </div>
  <br>
  <div class="col-md-3">
    <div id="itemsContainer"></div>

    <div class = "container content row">
      <h4 id = "links">Quick Links</h4>
      <ol id = "#regulations">
        <li><a href = "https://www1.nyc.gov/assets/doh/downloads/pdf/rii/fpc-manual.pdf" target="_blank">FPC Manual</a></li>
        <li><a href = "https://www1.nyc.gov/assets/doh/downloads/pdf/rii/ri-violation-penalty.pdf" target="_blank">Health Inspections Rules</a></li>
      </ol>
    </div>
  </div>
  <div class="col-md-8">

    <div id="chartContainer">
      <div id="chartDiv"></div>
    </div>
    <table id="dataTable" class="table none">
      <thead>
        <tr>
          <th>Date</th>
          <th>Quantity</th>
        </tr>
      </thead>
      <tbody id = "itemValues">
      </tbody>
    </table>
  </div>
</div>

<div id="addProductForm" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" style="color:black">Add New Product</h4>
      </div>
      <div class="modal-body" style="color:black">
        <form action="/add_product" method='POST' encType="multipart/form-data">
          {% csrf_token %}
          <div class = "container" style="width: 100%">
          {% for field in product_form.visible_fields %}
            <div class = "form-group">
              {{ field.label_tag }}
              {% render_field field class="form-control" %}
            </div>
          {% endfor %}
          </div>
          <div class = "container" style="width: 100%">
          {% for field in stock_form.visible_fields %}
            <div class = "form-group">
              {{ field.label_tag }}
              {% render_field field class="form-control" %}
            </div>
          {% endfor %}
          <input type="submit" name="" class = "btn btn-default" value="Add Product">
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div id="addUpdateForm" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" style="color:black">Update Product</h4>
      </div>
      <div class="modal-body" style="color:black">
        <form action="/update_stock" method='POST' encType="multipart/form-data">
          {% csrf_token %}
          <div class = "container" style="width=100%">
            <div>
              <select id="update_select" name='id'>
                <!--<option value="volvo">Volvo</option>-->
              </select>
            </div>
            <br>
            <label for="quantity">Quantity </label>
            <input type="text" name="quantity">
            <input type="submit" name="" class = "btn btn-default" value="Update Product">
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/pkr_user/home.html
{% extends "pkr_user/base.html" %}
{% load staticfiles %}
{% block body_block %}
<div class="container">
  <div class="jumbotron" id="welcome-banner">
    <center>
    	{% if user.is_authenticated %}
        	<h4>Welcome back, {{ user.username }}!</h3>
    	{% else %}
        	<h4>Register now to see what PKR can do for you.</h3>
    	{% endif %}
    </center>
  </div>
  <div class="jumbotron">
    <center>
        <img src="{% static "pkr_user/logo.png" %}" class = "logo" alt="logo" />
        <h2>Inventory Management Made Simple</h2>
    </center>
  </div>
  <div class="jumbotron">
    <center>
        <h2>Feature Rich</h2>
        <h4>Real-Time Updates ✔</h4>
        <h4>Price Comparisons ✔</h4>
        <h4>Data Reports ✔</h4>
    </center>
  </div>
  <div class="jumbotron">
      <h3>Manage anytime, anywhere.</h3>
      <h4>No matter where life takes you, your inventory will always be a click away.</h4>
  </div>
</div>

{% endblock %}

templates/pkr_user/linechart.html
<!DOCTYPE html>
<meta charset="utf-8">
<style> /* set the CSS */

body { font: 12px Arial;}

path {
    stroke: steelblue;
    stroke-width: 2;
    fill: none;
}

.axis path,
.axis line {
    fill: none;
    stroke: grey;
    stroke-width: 1;
    shape-rendering: crispEdges;
}

</style>
<body>

<!-- load the d3.js library -->
<script src="http://d3js.org/d3.v3.min.js"></script>

<script>

// Set the dimensions of the canvas / graph
var margin = {top: 30, right: 20, bottom: 30, left: 50},
    width = 600 - margin.left - margin.right,
    height = 270 - margin.top - margin.bottom;

// Parse the date / time
var parseDate = d3.time.format("%Y-%m-%d").parse;

// Set the ranges
var x = d3.time.scale().range([0, width]);
var y = d3.scale.linear().range([height, 0]);

// Define the axes
var xAxis = d3.svg.axis().scale(x)
    .orient("bottom").ticks(5);

var yAxis = d3.svg.axis().scale(y)
    .orient("left").ticks(5);

// Define the line
var valueline = d3.svg.line()
    .x(function(d) { return x(d.dateRecord); })
    .y(function(d) { return y(d.quantity); });

// Adds the svg canvas
var svg = d3.select("body")
    .append("svg")
        .attr("width", width + margin.left + margin.right + 20)
        .attr("height", height + margin.top + margin.bottom + 20)
    .append("g")
        .attr("transform",
              "translate(" + margin.left + "," + margin.top + ")");

// Get the data
d3.csv("data.csv", function(error, data) {
  console.log(data)
    data.forEach(function(d) {
        d.dateRecord = parseDate(d.dateRecord);
        d.quantity = +d.quantity;
    });

    // Scale the range of the data
    x.domain(d3.extent(data, function(d) { return d.dateRecord; }));
    y.domain([0, d3.max(data, function(d) { return d.quantity; })]);

    // Add the valueline path.
    svg.append("path")
        .attr("class", "line")
        .attr("d", valueline(data));

    // Add the X Axis
    svg.append("g")
        .attr("class", "x axis")
        .attr("transform", "translate(0," + height + ")")
        .call(xAxis);

    // Add the Y Axis
    svg.append("g")
        .attr("class", "y axis")
        .call(yAxis);

});

</script>
</body>

templates/pkr_user/login.html
{% extends "pkr_user/base.html" %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>
        <form method="post" action="{% url 'pkr_user:user_login' %}">
          {% csrf_token %}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login" color="black">
        </form>
    </div>
  </div>
{% endblock %}

templates/pkr_user/register.html
{% extends "pkr_user/base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Welcome to the PKR family!</h1>
      {% else %}
        <h2>Thanks for considering PKR!</h2>
        <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <div class = "container">
        {% for field in user_form.visible_fields %}
          <div class = "form-group">
            {{ field.label_tag }}
            {% render_field field class="form-control" %}
          </div>
          {% endfor %}
        </div>
        <div class = "container">
        {% for field in customer_form.visible_fields %}
          <div class = "form-group">
            {{ field.label_tag }}
            {% render_field field class="form-control" %}
          </div>
        {% endfor %}
        </div>
        <div class = "container">
          <input type="submit" name="" class = "btn btn-primary" value="Register">
        </div>
        </form>
      {% endif %}

    </div>

  </div>

{% endblock %}